# Generated by Django 4.1.1 on 2022-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locais",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(max_length=10, null=True)),
                ("nome", models.CharField(max_length=100)),
                ("radio", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
