# Generated by Django 4.1.1 on 2022-09-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_locais_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="locais",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
