# Generated by Django 4.1.1 on 2022-09-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_locais_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locais",
            old_name="data",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="locais",
            old_name="nome",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="locais",
            name="radio",
        ),
        migrations.AddField(
            model_name="locais",
            name="period",
            field=models.CharField(
                choices=[("m", "MANHÃ"), ("t", "TARDE"), ("n", "NOITE")],
                max_length=5,
                null=True,
            ),
        ),
    ]
